- space-backend/app/Http/Controllers/BandeiraController.php
- space-backend/app/Models/CalculoBandeira.php
- space-backend/composer.lock
- space-backend/database/migrations/2024_11_04_145703_create_calculo_bandeiras_table.php
- space-backend/routes/api.php
Foi feita a criação de uma rota para o calculo das bandeiras para poder salvar os dados no banco de dados -  Sendo feita a criação do Controller, Model e Migration.
> feet: Add bandeira endpoint

- space-backend/.env
- space-backend/app/Http/Controllers/ContaController.php
- space-backend/app/Http/Controllers/CustoBandeiraController.php
- space-backend/app/Http/Resources/ContaResource.php
- space-backend/app/Models/Config.php
- space-backend/database/migrations/2024_11_04_145703_create_custo_bandeiras_table.php
- space-backend/database/migrations/2024_11_07_175833_create_configs_table.php
- space-backend/docs/.http/create_conta.http
- space-backend/docs/.http/create_custo_bandeira
- space-backend/docs/.http/create_user.http
- space-backend/docs/.http/get_user.http
- space-backend/docs/.http/list_conta.http
- space-backend/docs/.http/login.http
- space-backend/docs/.http/user.http
- space-backend/routes/api.php
Adiciona rotas para contas a pagar e a receber.
> Conta atualizada

- docs/.http/super-admin/delete_module.http
- docs/.http/super-admin/delete_role_modules.http
- docs/.http/super-admin/delete_user_roles.http
- docs/.http/super-admin/get_configs.http
- docs/.http/super-admin/upsert_config.http
> feat: Add Test routes

- space-backend/init-container.sh
> fix: Change to dinamic REDIS_HOST

- docker/Dockerfile
> feat: Install Redis from Dockerfile

- docs/.http/webhook/webhook.http
- space-backend/app/Http/Controllers/ChatOctaController.php
- space-backend/database/migrations/2024_12_17_141652_create_octa_webhook_table.php
> fix: Change octa_id for just id on octa-webhook method

- docs/.http/clientes-consolidados/get-clientes-consolidados.http
- docs/.http/webhook/webhook.http
- space-backend/app/Http/Controllers/ChatOctaController.php
- space-backend/app/Http/Controllers/ClientesConsolidadosController.php
- space-backend/app/Models/CrmCliente.php
- space-backend/app/Models/OctaWebHook.php
- space-backend/routes/api.php
Consolida os dados de clientes e cria uma rota
> feat: Add CrmCliente

- space-backend/init-container.sh
> feat: Increase memory limit (2)

- docker/Dockerfile
- docs/.http/clientes-consolidados/get-clientes-consolidados.http
- space-backend/init-container.sh
Definindo o limite maximo de memória no init-container.sh (não mais diretamente na ENV do Dockerfile)
> feat: Increase memory limit (4)

- space-backend/database/migrations/2024_10_30_135037_create_produtos_categorias_table.php
- space-backend/routes/api.php
Permite o vendedor consultar feriados.
> feat: Allow comercial role get feriados

- docs/.http/orcamento/aprova-orcamento.http
- docs/.http/produto/get_all_produtos_orcamento_consolidado.http
- docs/.http/produto/get_all_produtos_orcamento_query.http
- docs/.http/user/login.http
- space-backend/app/Http/Controllers/ProdutoOrcamentoController.php
- space-backend/app/Http/Controllers/ProdutosPersonalizadController.php
- space-backend/app/Models/ProdutoOrcamento.php
- space-backend/database/migrations/2025_01_17_131133_create_produtos_bandeiras_oficiais.php
- space-backend/database/migrations/2025_01_17_150719_create_produtos_orcamento_view.php
- space-backend/routes/api.php
> feat: Add bandeiras oficiais

- docs/.http/calendar/feriado-ano-mes.http
- space-backend/app/Http/Controllers/CalendarEventController.php
- space-backend/routes/api.php
Reduz requisições para feriados
> feat: Refactor holiday calculation logic to reduce requests

- .github/workflows/homolog.yml
- .github/workflows/prod.yml
- docs/.http/cliente-cadastro/upsert-cliente-cadastro.http
- docs/.http/orcamento/get-all-orcamentos-aprovados.http
- space-backend/app/Http/Controllers/ClienteCadastroController.php
- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/app/Models/ClienteCadastro.php
- space-backend/app/Models/Orcamento.php
- space-backend/database/migrations/2025_01_21_170232_create_clientes_cadastro_table.php
- space-backend/database/migrations/2025_01_21_182449_create_orcamento_cliente_cadastro_table.php
- space-backend/routes/api.php
> feat: Add backoffice

- space-backend/app/Models/Orcamento.php
roll back status() on Orcamento model
> fix: Roll back status() method on Orcamento model

- docs/.http/user/validate_token.http
- space-backend/database/migrations/2025_01_28_170845_create_links_table.php
fix: Update link original_url field to text
> fix: Update link original_url field to text

- docs/.http/clientes-consolidados/get-clientes-consolidados.http
- docs/.http/produto/get_all_produtos.http
- docs/.http/produto/get_all_produtos_orcamento_consolidado.http
- docs/.http/user/validate_token.http
- docs/.http/vendas/relatorio/quantidade-orcamentos-entrega.http
- docs/.http/vendas/relatorio/quantidade-orcamentos.http
- docs/.http/vendas/relatorio/status-orcamento.http
- space-backend/.env
- space-backend/app/Http/Controllers/FreteController.php
- space-backend/app/Http/Controllers/VendasController.php
- space-backend/routes/api.php
Orçamento por Data
Novo Relatório da Arte Arena
> Relatórios de Vendas - Orçamento por Data

- space-backend/app/Http/Controllers/VendasController.php
Correção das rotas removendo user_id
> Leandro orcamentos dia

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/database/migrations/2025_02_04_202617_add_antecipacao_columns_to_orcamentos_table.php
> Antecipação - main

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/app/Models/Orcamento.php
- space-backend/database/migrations/2025_02_12_164249_add_brinde_columns_to_orcamentos_table.php
Brindes (migration and controller) {Orcamento}
> feat: Brindes

- space-backend/app/Http/Controllers/VendasController.php
fix: Clean the vendasControler.
> Gustavo branch

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/app/Models/OrcamentoStatus.php
- space-backend/database/migrations/2025_02_13_140819_add_specific_status_fields_to_orcamentos_status_table.php
- space-backend/routes/api.php
Status específicos (orcamentos)
> Status específicos (orcamentos)

- docs/.http/orcamento/orcamentos-status/update_status_aprovacao_arte_arena.http
- docs/.http/orcamento/orcamentos-status/update_status_pagamento.http
- docs/.http/orcamento/orcamentos-status/update_status_producao_esboco.http
- space-backend/app/Http/Controllers/OrcamentoController.php
feat: Add columns to controller (specific orcamentos status)
> feat: Add columns to controller (specific orcamentos status)

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/routes/api.php
add new route for approve status on orcamento buscar
> feat: add new route orcamentos for approve buttons on frontend

- space-backend/routes/api.php
fix: Remove duplicated line on api.php
> fix: Remove duplicated line on api.php

- docs/.http/clientes-consolidados/get-search-clientes-consolidados.http
- docs/.http/orcamento/get-all-orcamento-with-status.http
- space-backend/app/Http/Controllers/ClientesConsolidadosController.php
- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/routes/api.php
Isolate search clientes consolidados from clientes consolidados
> Isolate search clientes consolidados from clientes consolidados

- docs/.http/orcamento/get-orcamento.http
- space-backend/app/Http/Controllers/OrcamentoController.php
refeat: Return 204 status for non content response on get-orcamento
> refeat: Return 204 status for non content response on get-orcamento

- space-backend/routes/api.php
> feat: Add lalamove route

- space-backend/app/Http/Controllers/FreteController.php
feat: Add getFreteLalamove method
> feat: Add getFreteLalamove method

- space-backend/app/Http/Controllers/FreteController.php
> Adjust LALAMOVE URL Backend

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/app/Models/OrcamentoStatusEtapa.php
- space-backend/database/migrations/2025_02_21_175156_create_orcamentos_status_etapa_table.php
- space-backend/routes/api.php
feat: add new migration table etapa on ocamento_status
> feat: add new migration table etapa on ocamento_status

- space-backend/app/Http/Controllers/ClienteCadastroController.php
feat: add insertions on pedidos, add new response, add validation for the sallesman.
> feat: add insertions on pedidos, add new response, add validation for the sallesman.

- space-backend/database/migrations/2025_02_25_184913_create_orcamentos_status_esboco_table.php
feat: Add orcamentos_status_esboco table
> feat: Add orcamentos_status_esboco table

- space-backend/app/Http/Controllers/PedidoController.php
- space-backend/database/migrations/2025_02_26_180141_add_collumn_to_pedidos_codigo_rastramento.php
- space-backend/routes/api.php
Controller and migration (!) - Add new column to pedidos table
> Gustavo pedido

- space-backend/app/Http/Controllers/ClienteCadastroController.php
- space-backend/app/Http/Controllers/PedidoController.php
- space-backend/routes/api.php
Feat: add new validation for the button and dinamic loading with useEffect
> feat: add new routes for get all pedidos and get pedido

- docs/.http/produto/pacotes/get-pacotes.http
- docs/.http/produto/pacotes/upsert-pacote-DIAMANTE.http
- docs/.http/produto/pacotes/upsert-pacote-OURO.http
- docs/.http/produto/pacotes/upsert-pacote-PRATA.http
- docs/.http/produto/pacotes/upsert-pacote-PREMIUM.http
- docs/.http/produto/pacotes/upsert-pacote-PROFISSIONAL.http
- docs/.http/produto/pacotes/upsert-pacote-START.http
> docs: Add upsert-pacote tests

- docs/.http/produto/pacotes/delete-pacote.http
- docs/.http/produto/pacotes/get-pacotes.http
- space-backend/database/migrations/2025_03_04_123113_add_prazo_producao_column_to_orcamentos_table.php
Adicionamos uma coluna para prazo de produlção na tabela orçamentos!
> feat: Add prazo_producao column to orcamentos table

- space-backend/app/Http/Controllers/OrcamentoController.php
- space-backend/app/Models/Orcamento.php
feat: Add prazo_producao to Orcamento Model and Controller
> feat: Add prazo_producao to Orcamento Model and Controller

- space-backend/database/migrations/2025_03_04_150705_add_clounm_valor_fatura_data_fatura_ocamento_status.php
feat: add migration add_clounm_valor_fatura_data_fatura_ocamento_status
> feat: add migration add_clounm_valor_fatura_data_fatura_ocamento_status

- space-backend/app/Models/Material.php
feat: Fix materials table name
> feat: Fix materials table name

- docs/.http/tiny/produto/search_pedidos.http
- space-backend/app/Http/Controllers/PedidoArteFinalController.php
- space-backend/routes/api.php
feat: Add ArteFinal send to print
> feat: Add ArteFinal send to print

- space-backend/database/seeders/RoleSeeder.php
feat: Add backoffice role to RoleSeeder
> feat: Add backoffice role to RoleSeeder

- space-backend/app/Http/Controllers/PedidoArteFinalController.php
- space-backend/routes/api.php
Melhorias no campo de Observação, garantindo que seja salvo ao pressionar Enter, sempre exibido usando o CustomTextField (padrão do template), perfomance dele foi revisada para evitar qualquer efeito colateral sobre requisições para o backend e re-renderizações do frontend.
> Leandro gustavo refact producao

- space-backend/app/Http/Controllers/PedidoArteFinalController.php
- space-backend/routes/api.php
fix: Add log messages and validation to backoffice routes
> fix: Add log messages and validation to backoffice routes

- docs/.http/super-admin/get_configs_prazos.http
- docs/.http/super-admin/upsert_configs_prazos.http
- space-backend/app/Http/Controllers/SuperAdminController.php
- space-backend/app/Models/ConfigPrazos.php
- space-backend/database/migrations/2025_04_04_125929_create_configs_prazos_table.php
- space-backend/routes/api.php
fix: Rename columns to Super Admin Config Prazos
> fix: Rename columns to Super Admin Config Prazos
